// Copyright Yubico AB
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

// MARK: - PreviewSign Extension

extension CTAP2.Extension {
    /// The previewSign extension for delegated signing.
    ///
    /// Implements version 4 of the sign CTAP2 extension.
    ///
    /// https://yubicolabs.github.io/webauthn-sign-extension/4/#sctn-sign-extension
    ///
    /// - Warning: This extension is currently in draft status and should be
    ///   considered experimental. It is not part of the stable API of this library.
    public struct PreviewSign: Sendable {
        static let identifier: Identifier = .previewSign

        /// Creates a PreviewSign extension instance.
        ///
        /// - Throws: `CTAP2.SessionError.extensionNotSupported` if previewSign is not supported.
        public init(session: CTAP2.Session) async throws(CTAP2.SessionError) {
            let info = try await session.cachedInfo
            guard info.extensions.contains(Self.identifier) else {
                throw .extensionNotSupported(Self.identifier, source: .here())
            }
        }

        /// Checks if the authenticator supports previewSign.
        public static func isSupported(by session: CTAP2.Session) async throws(CTAP2.SessionError) -> Bool {
            let info = try await session.cachedInfo
            return info.extensions.contains(identifier)
        }

        /// Operations for MakeCredential.
        public var makeCredential: MakeCredentialOperations {
            MakeCredentialOperations()
        }

        /// Operations for GetAssertion.
        public var getAssertion: GetAssertionOperations {
            GetAssertionOperations()
        }
    }
}

// MARK: - CBOR Keys

extension CTAP2.Extension.PreviewSign {
    fileprivate enum MakeCredentialKey: Int {
        case algorithm = 0x03
        case flags = 0x04
        case attestationObject = 0x07
    }

    fileprivate enum GetAssertionKey: Int {
        case keyHandle = 0x02
        case tbsOrSignature = 0x06
        case additionalArgs = 0x07
    }

    fileprivate enum AttestationObjectKey: Int {
        case fmt = 0x01
        case authData = 0x02
        case attStmt = 0x03
    }
}

// MARK: - GeneratedKey

extension CTAP2.Extension.PreviewSign {
    /// A key pair generated by the authenticator during registration.
    public struct GeneratedKey: Sendable, Equatable {
        /// The key handle used to reference the generated key.
        public let keyHandle: Data

        /// The CBOR-encoded COSE public key.
        public let publicKey: Data

        /// The algorithm used for the generated key.
        public let algorithm: COSE.Algorithm

        /// The raw CBOR-encoded attestation object for the generated key.
        public let attestationObject: Data

        public init(keyHandle: Data, publicKey: Data, algorithm: COSE.Algorithm, attestationObject: Data) {
            self.keyHandle = keyHandle
            self.publicKey = publicKey
            self.algorithm = algorithm
            self.attestationObject = attestationObject
        }
    }
}

// MARK: - MakeCredential Operations

extension CTAP2.Extension.PreviewSign {
    /// MakeCredential operations for previewSign.
    public struct MakeCredentialOperations: Sendable {

        /// Creates a MakeCredential input to generate a signing key pair.
        ///
        /// - Parameters:
        ///   - algorithms: COSE algorithm identifiers the RP supports.
        ///   - flags: Flags byte (bit 0: UP required, bit 2: UV required).
        public func input(
            algorithms: [COSE.Algorithm],
            flags: UInt8
        ) -> CTAP2.Extension.MakeCredential.Input {
            typealias Key = MakeCredentialKey
            var map: [CBOR.Value: CBOR.Value] = [:]
            map[.int(Key.algorithm.rawValue)] = .array(algorithms.map { .int($0.rawValue) })
            map[.int(Key.flags.rawValue)] = .unsignedInt(UInt64(flags))
            return CTAP2.Extension.MakeCredential.Input(
                encoded: [CTAP2.Extension.PreviewSign.identifier: .map(map)]
            )
        }

        /// Extracts the generated key from a MakeCredential response.
        public func output(
            from response: CTAP2.MakeCredential.Response
        ) throws(CTAP2.SessionError) -> GeneratedKey? {
            typealias Key = MakeCredentialKey
            guard
                let extMap = response.authenticatorData.extensions?[
                    CTAP2.Extension.PreviewSign.identifier
                ]?.mapValue
            else {
                return nil
            }

            guard
                let algValue = extMap[.int(Key.algorithm.rawValue)]?.intValue,
                let attObjBytes: Data = response.unsignedExtensionOutputs?[
                    CTAP2.Extension.PreviewSign.identifier.value
                ]?.mapValue?[.int(Key.attestationObject.rawValue)]?.dataValue,
                let attObjCBOR: CBOR.Value = try? attObjBytes.decode(),
                let authDataBytes: Data = attObjCBOR.mapValue?[.int(AttestationObjectKey.authData.rawValue)]?
                    .cborDecoded(),
                let authData = WebAuthn.AuthenticatorData(data: authDataBytes),
                let attestedData = authData.attestedCredentialData
            else {
                throw .responseParseError(
                    "previewSign: invalid generateKey response",
                    source: .here()
                )
            }

            // Re-encode attestation object with string keys (WebAuthn JSON convention)
            // CTAP uses integer keys (1=fmt, 2=authData, 3=attStmt) but the WebAuthn
            // layer expects string keys ("fmt", "authData", "attStmt").
            let attObjMap = attObjCBOR.mapValue!
            var stringKeyedAttObj: [CBOR.Value: CBOR.Value] = [:]
            stringKeyedAttObj[.textString("fmt")] = attObjMap[.int(AttestationObjectKey.fmt.rawValue)]
            stringKeyedAttObj[.textString("authData")] = attObjMap[.int(AttestationObjectKey.authData.rawValue)]
            stringKeyedAttObj[.textString("attStmt")] = attObjMap[.int(AttestationObjectKey.attStmt.rawValue)]
            let reEncodedAttObj = CBOR.Value.map(stringKeyedAttObj).encode()

            return GeneratedKey(
                keyHandle: attestedData.credentialId,
                publicKey: attestedData.credentialPublicKey.cbor().encode(),
                algorithm: COSE.Algorithm(rawValue: algValue),
                attestationObject: reEncodedAttObj
            )
        }
    }
}

// MARK: - GetAssertion Operations

extension CTAP2.Extension.PreviewSign {
    /// GetAssertion operations for previewSign.
    public struct GetAssertionOperations: Sendable {

        /// Creates a GetAssertion input to sign data with a previously generated key.
        ///
        /// - Parameters:
        ///   - keyHandle: The key handle from the generated key.
        ///   - tbs: The data to be signed (typically a hash).
        ///   - additionalArgs: Optional CBOR-encoded additional arguments (e.g., ARKG derivation parameters).
        public func input(
            keyHandle: Data,
            tbs: Data,
            additionalArgs: Data? = nil
        ) -> CTAP2.Extension.GetAssertion.Input {
            typealias Key = GetAssertionKey
            var map: [CBOR.Value: CBOR.Value] = [:]
            map[.int(Key.keyHandle.rawValue)] = .byteString(keyHandle)
            map[.int(Key.tbsOrSignature.rawValue)] = .byteString(tbs)
            if let additionalArgs {
                map[.int(Key.additionalArgs.rawValue)] = .byteString(additionalArgs)
            }
            return CTAP2.Extension.GetAssertion.Input(
                encoded: [CTAP2.Extension.PreviewSign.identifier: .map(map)]
            )
        }

        /// Extracts the signature from a GetAssertion response.
        public func output(from response: CTAP2.GetAssertion.Response) -> Data? {
            typealias Key = GetAssertionKey
            return response.authenticatorData.extensions?[
                CTAP2.Extension.PreviewSign.identifier
            ]?.mapValue?[.int(Key.tbsOrSignature.rawValue)]?.dataValue
        }
    }
}
