// Copyright Yubico AB
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

// MARK: - PreviewSign Extension

extension CTAP2.Extension {
    /// The previewSign extension for delegated signing (draft).
    ///
    /// This extension allows an authenticator to generate a master key pair
    /// during registration and sign data using derived keys during authentication.
    ///
    /// - Warning: This extension is currently in draft status and should be
    ///   considered experimental. It is not part of any published FIDO specification.
    public struct PreviewSign: Sendable {
        /// The extension identifier for previewSign.
        static let identifier: Identifier = .previewSign

        // MARK: - Initializer

        /// Creates a PreviewSign extension instance.
        ///
        /// - Parameter session: The CTAP2 session to check for support.
        /// - Throws: `CTAP2.SessionError.extensionNotSupported` if previewSign is not supported.
        public init(session: CTAP2.Session) async throws(CTAP2.SessionError) {
            let info = try await session.cachedInfo
            guard info.extensions.contains(Self.identifier) else {
                throw .extensionNotSupported(Self.identifier, source: .here())
            }
        }

        /// Checks if the authenticator supports previewSign.
        ///
        /// - Parameter session: The CTAP2 session to check.
        /// - Returns: `true` if the authenticator supports previewSign.
        public static func isSupported(by session: CTAP2.Session) async throws(CTAP2.SessionError) -> Bool {
            let info = try await session.cachedInfo
            return info.extensions.contains(identifier)
        }

        // MARK: - Operations

        /// Operations for MakeCredential.
        public var makeCredential: MakeCredentialOperations {
            MakeCredentialOperations()
        }

        /// Operations for GetAssertion.
        public var getAssertion: GetAssertionOperations {
            GetAssertionOperations()
        }
    }
}

// MARK: - GeneratedKey

extension CTAP2.Extension.PreviewSign {
    /// A key pair generated by the authenticator during registration.
    public struct GeneratedKey: Sendable, Equatable {
        /// The key handle used to reference the generated key.
        public let keyHandle: Data

        /// The CBOR-encoded COSE public key.
        public let publicKey: Data

        /// The algorithm used for the generated key.
        public let algorithm: COSE.Algorithm

        /// The raw CBOR-encoded attestation object for the generated key.
        public let attestationObject: Data

        public init(keyHandle: Data, publicKey: Data, algorithm: COSE.Algorithm, attestationObject: Data) {
            self.keyHandle = keyHandle
            self.publicKey = publicKey
            self.algorithm = algorithm
            self.attestationObject = attestationObject
        }
    }
}

// MARK: - MakeCredential Operations

extension CTAP2.Extension.PreviewSign {
    /// MakeCredential operations for previewSign.
    public struct MakeCredentialOperations: Sendable {

        /// Creates a MakeCredential input to generate a signing key pair.
        ///
        /// - Parameters:
        ///   - algorithms: List of COSE algorithm identifiers the RP supports.
        ///   - flags: Flags byte (bit 0: UP required, bit 2: UV required).
        /// - Returns: An extension input for MakeCredential.
        public func input(
            algorithms: [COSE.Algorithm],
            flags: UInt8
        ) -> CTAP2.Extension.MakeCredential.Input {
            var map: [CBOR.Value: CBOR.Value] = [:]
            map[.int(3)] = .array(algorithms.map { .int($0.rawValue) })
            map[.int(4)] = .unsignedInt(UInt64(flags))
            return CTAP2.Extension.MakeCredential.Input(
                encoded: [CTAP2.Extension.PreviewSign.identifier: .map(map)]
            )
        }

        /// Extracts the generated key from a MakeCredential response.
        ///
        /// - Parameter response: The MakeCredential response from the authenticator.
        /// - Returns: The generated key, or `nil` if not present.
        public func output(
            from response: CTAP2.MakeCredential.Response
        ) throws(CTAP2.SessionError) -> GeneratedKey? {
            guard
                let extMap = response.authenticatorData.extensions?[
                    CTAP2.Extension.PreviewSign.identifier
                ]?.mapValue
            else {
                return nil
            }
            guard let algValue = extMap[.int(3)]?.intValue else {
                throw .responseParseError(
                    "previewSign: missing algorithm in signed extension data",
                    source: .here()
                )
            }
            let algorithm = COSE.Algorithm(rawValue: algValue)

            // The attestation object carries its own attestation statement, so it's in unsigned outputs
            guard
                let unsignedExt = response.unsignedExtensionOutputs?[
                    CTAP2.Extension.PreviewSign.identifier.value
                ]
            else {
                throw .responseParseError(
                    "previewSign: missing unsigned extension output",
                    source: .here()
                )
            }
            guard let unsignedMap = unsignedExt.mapValue,
                let attObjCBOR = unsignedMap[.int(7)]
            else {
                throw .responseParseError(
                    "previewSign: missing attestation object in unsigned output",
                    source: .here()
                )
            }

            // Key 7 is the attestation object — either CBOR bytestring or inline map
            let attObjBytes: Data
            let attObjMap: [CBOR.Value: CBOR.Value]
            if let bytes = attObjCBOR.dataValue {
                attObjBytes = bytes
                let decoded: CBOR.Value
                do throws(CBOR.Error) {
                    guard let value: CBOR.Value = try bytes.decode() else {
                        throw .unexpectedEndOfData
                    }
                    decoded = value
                } catch {
                    throw .responseParseError(
                        "previewSign: failed to decode inner attestation object: \(error)",
                        source: .here()
                    )
                }
                guard let map = decoded.mapValue else {
                    throw .responseParseError(
                        "previewSign: inner attestation object is not a CBOR map",
                        source: .here()
                    )
                }
                attObjMap = map
            } else if let map = attObjCBOR.mapValue {
                attObjBytes = attObjCBOR.encode()
                attObjMap = map
            } else {
                throw .responseParseError(
                    "previewSign: unexpected attestation object format",
                    source: .here()
                )
            }

            guard let authDataBytes: Data = attObjMap[.int(2)]?.cborDecoded() else {
                throw .responseParseError(
                    "previewSign: missing authData in inner attestation object",
                    source: .here()
                )
            }

            guard let authData = WebAuthn.AuthenticatorData(data: authDataBytes),
                let attestedData = authData.attestedCredentialData
            else {
                throw .responseParseError(
                    "previewSign: failed to parse attested credential data",
                    source: .here()
                )
            }

            let publicKeyBytes = attestedData.credentialPublicKey.cbor().encode()

            return GeneratedKey(
                keyHandle: attestedData.credentialId,
                publicKey: publicKeyBytes,
                algorithm: algorithm,
                attestationObject: attObjBytes
            )
        }
    }
}

// MARK: - GetAssertion Operations

extension CTAP2.Extension.PreviewSign {
    /// GetAssertion operations for previewSign.
    public struct GetAssertionOperations: Sendable {

        /// Creates a GetAssertion input to sign data with a previously generated key.
        ///
        /// - Parameters:
        ///   - keyHandle: The key handle from the generated key.
        ///   - tbs: The data to be signed (typically a hash).
        ///   - additionalArgs: Optional CBOR-encoded additional arguments (e.g., ARKG derivation parameters).
        /// - Returns: An extension input for GetAssertion.
        public func input(
            keyHandle: Data,
            tbs: Data,
            additionalArgs: Data? = nil
        ) -> CTAP2.Extension.GetAssertion.Input {
            var map: [CBOR.Value: CBOR.Value] = [:]
            map[.int(2)] = .byteString(keyHandle)
            map[.int(6)] = .byteString(tbs)
            if let additionalArgs {
                map[.int(7)] = .byteString(additionalArgs)
            }
            return CTAP2.Extension.GetAssertion.Input(
                encoded: [CTAP2.Extension.PreviewSign.identifier: .map(map)]
            )
        }

        /// Extracts the signature from a GetAssertion response.
        ///
        /// - Parameter response: The GetAssertion response from the authenticator.
        /// - Returns: The signature bytes, or `nil` if not present.
        public func output(from response: CTAP2.GetAssertion.Response) -> Data? {
            response.authenticatorData.extensions?[
                CTAP2.Extension.PreviewSign.identifier
            ]?.mapValue?[.int(6)]?.dataValue
        }
    }
}
