name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Test (macOS & iOS)
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.4
        run: |
          sudo xcode-select -s /Applications/Xcode_16.4.app
          xcodebuild -version

      - name: Check lint rules
        id: lint
        shell: bash
        run: |
          xcrun swift-format lint . \
          --parallel \
          --recursive \
          --strict

      - name: Find iOS simulator UDID
        id: sim
        shell: bash
        run: |
          SIM_NAME="iPhone"

          UDID=$(xcrun simctl list devices available \
          | grep -m1 -E "${SIM_NAME}.*\\(" \
          | sed -E 's/.*\(([0-9A-F-]+)\).*/\1/')

          echo "udid=$UDID" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run tests (macOS)
        run: swift test -v --parallel

      - name: Build and run unit tests (iOS Simulator)
        run: |
          xcodebuild test -scheme YubiKitTests \
            -destination "platform=iOS Simulator,id=${{ steps.sim.outputs.udid }}" \
            CODE_SIGNING_ALLOWED=NO
