name: Deploy DocC

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['v*']

permissions:
  contents: write      # push to gh-pages

concurrency: docs-main # 1 deploy at a time

env:
  DOCS_PATH: ./docs
  PAGES_BRANCH: gh-pages

jobs:
  deploy-docs:
    runs-on: macos-26-xlarge

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      
      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Determine deployment paths
        id: path
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "base_path=yubikit-swift" >> $GITHUB_OUTPUT
            echo "target_folder=." >> $GITHUB_OUTPUT
          else
            echo "base_path=yubikit-swift/${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "target_folder=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Docs
        run: |
          xcodebuild docbuild \
            -scheme YubiKit \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath .build

          $(xcrun --find docc) process-archive \
            transform-for-static-hosting .build/Build/Products/Debug-iphonesimulator/YubiKit.doccarchive \
            --output-path ${{ env.DOCS_PATH }} \
            --hosting-base-path ${{ steps.path.outputs.base_path }}

      - name: Redirect root to documentation
        run: |
          cat > "${{ env.DOCS_PATH }}/index.html" <<'HTML'
          <!doctype html>
          <meta http-equiv="refresh" content="0; url=./documentation/yubikit">
          HTML

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          folder: ${{ env.DOCS_PATH }}
          branch: ${{ env.PAGES_BRANCH }}
          target-folder: ${{ steps.path.outputs.target_folder }}
          clean-exclude: pr-* v*
          force: false
          token: ${{ secrets.GITHUB_TOKEN }}
