name: Detect public API changes

on:
  pull_request:
    branches: [ "main", "release/**" ]
    paths:
      - 'YubiKit/**/*.swift'
      - 'Package.swift'
      - '.github/workflows/public-api-diff.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  public-api-diff:
    runs-on: macos-26-xlarge
    
    steps:
    - name: Checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        fetch-depth: 0

    - name: Setup Environment
      uses: ./.github/actions/setup-env
    
    - name: Define Diff Versions
      env:
        HEAD_REF: ${{ github.head_ref }}
        BASE_REF: ${{ github.event.pull_request.base.ref }}
        HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        SERVER_URL: ${{ github.server_url }}
        REPO: ${{ github.repository }}
      run: |
        NEW="${HEAD_REF}~${SERVER_URL}/${HEAD_REPO}.git"
        OLD="${BASE_REF}~${SERVER_URL}/${REPO}.git"

        echo "OLD_VERSION=$OLD" >> "$GITHUB_ENV"
        echo "NEW_VERSION=$NEW" >> "$GITHUB_ENV"
    
    - name: Detect YubiKit Public API Changes (macOS)
      uses: Adyen/adyen-swift-public-api-diff@9ed54d9884b1a8f0e2c1ecde353793ea8ce7132b # 0.11.2
      with:
        platform: macOS
        new: ${{ env.NEW_VERSION }}
        old: ${{ env.OLD_VERSION }}

    - name: Detect YubiKit Public API Changes (iOS)
      uses: Adyen/adyen-swift-public-api-diff@9ed54d9884b1a8f0e2c1ecde353793ea8ce7132b # 0.11.2
      with:
        platform: iOS
        new: ${{ env.NEW_VERSION }}
        old: ${{ env.OLD_VERSION }}
 
